import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

import { styled } from "@/styled-system/jsx";

import Footer from "@/components/footer";
import Navigation from "@/components/navigation";

export const metadata: Metadata = {
  title: "Emily Lewandowki",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${generalSans.variable}  ${denton.variable}`}>
      <Body>
        <Navigation theme="dark" />
        {children}
        <Footer />
        <Noise />
      </Body>
    </html>
  );
}

// FONTS

const generalSans = localFont({
  src: "../fonts/general-sans.woff2",
  variable: "--font-generalSans",
  fallback: ["system-ui", "arial"],
});

const denton = localFont({
  src: [
    {
      path: "../fonts/denton.woff2",
      style: "normal",
      weight: "200 700",
    },
    {
      path: "../fonts/denton-italic.woff2",
      style: "italic",
      weight: "200 700",
    },
  ],
  variable: "--font-denton",
});

// STYLES

const Body = styled("body", {
  base: {
    background: "$background",
    width: "100%",
    height: "100%",
    minHeight: "100vh",
    display: "flex",
    flexDir: "column",
  },
});

const Noise = styled("div", {
  base: {
    backgroundImage: "url(/noise.png)",
    backgroundRepeat: "repeat",
    backgroundSize: "182px",
    position: "absolute",
    inset: "0",
    opacity: "0.0325",
    pointerEvents: "none",
  },
});
